### ISSUE TITLE
Monitoring through Admin Web UI gives error with applications using Application Versions feature

### ISSUE THREAD

**Issue by jaceabreu** [eclipse-ee4j/glassfish#24079]
When using Glassfish Monitoring Service from Admin Web UI, viewing monitor data for applications fails with an error on applications that are published with Application Versioning name schema (app-name:version-id); error: "Invalid module name PermitSearch:2.2.0-SNAPSHOT. Application  PermitSearch:2.2.0-SNAPSHOT does not contain module with name  PermitSearch:2.2.0-SNAPSHOT."

## Environment Details
* GlassFish Version (and build number): Eclipse GlassFish 6.2.5 (build 6.x-b66-g0159b68 2022-02-12T17:39:59+0000)
* JDK version: OpenJDK 17.0.2
* OS:  Ubuntu Server 22.04 LTS
* Database: PostgreSQL 14

----------

## Problem Description
When utilizing Applications Version feature for deployed applications, the monitoring service cannot load application components, listing an error, instead.
Problem is easily reproducible and happens every time.
There is no stack trace available, but here is the server.log entries (from a clean log file) after viewing the error.
```
[2022-08-15T09:33:20.936-0400] [glassfish 6.2] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=40 _ThreadName=admin-listener(5)] [timeMillis: 1660570400936] [levelValue: 1000] [[

  RestResponse.getResponse&#x28;&#x29; gives FAILURE.  endpoint &#x3d; &#x27;https&#x3a;&#x2f;&#x2f;localhost&#x3a;4848&#x2f;management&#x2f;domain&#x2f;applications&#x2f;application&#x2f;PermitSearch&#x3a;2.2.0-SNAPSHOT&#x2f;list-sub-components&#x27;&#x3b; attrs &#x3d; &#x27;&#x7b;appname&#x3d;PermitSearch&#x3a;2.2.0-SNAPSHOT, id&#x3d;PermitSearch&#x3a;2.2.0-SNAPSHOT&#x7d;&#x27;]]



[2022-08-15T09:33:20.936-0400] [glassfish 6.2] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=40 _ThreadName=admin-listener(5)] [timeMillis: 1660570400936] [levelValue: 1000] [[

  Error in getSubComponents ; 

endpoint = https://localhost:4848/management/domain/applications/application/PermitSearch:2.2.0-SNAPSHOT/list-sub-componentsattrs={appname=PermitSearch:2.2.0-SNAPSHOT, id=PermitSearch:2.2.0-SNAPSHOT}method=GET]]



[2022-08-15T09:33:23.901-0400] [glassfish 6.2] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=36 _ThreadName=admin-listener(1)] [timeMillis: 1660570403901] [levelValue: 1000] [[

  RestResponse.getResponse&#x28;&#x29; gives FAILURE.  endpoint &#x3d; &#x27;https&#x3a;&#x2f;&#x2f;localhost&#x3a;4848&#x2f;management&#x2f;domain&#x2f;applications&#x2f;application&#x2f;PermitSearch&#x3a;2.2.0-SNAPSHOT&#x2f;list-sub-components&#x27;&#x3b; attrs &#x3d; &#x27;&#x7b;appname&#x3d;PermitSearch&#x3a;2.2.0-SNAPSHOT, id&#x3d;PermitSearch&#x3a;2.2.0-SNAPSHOT&#x7d;&#x27;]]



[2022-08-15T09:33:23.901-0400] [glassfish 6.2] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=36 _ThreadName=admin-listener(1)] [timeMillis: 1660570403901] [levelValue: 1000] [[

  Error in getSubComponents ; 

endpoint = https://localhost:4848/management/domain/applications/application/PermitSearch:2.2.0-SNAPSHOT/list-sub-componentsattrs={appname=PermitSearch:2.2.0-SNAPSHOT, id=PermitSearch:2.2.0-SNAPSHOT}method=GET]]



[2022-08-15T09:33:23.946-0400] [glassfish 6.2] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=36 _ThreadName=admin-listener(1)] [timeMillis: 1660570403946] [levelValue: 1000] [[

  RestResponse.getResponse&#x28;&#x29; gives FAILURE.  endpoint &#x3d; &#x27;https&#x3a;&#x2f;&#x2f;localhost&#x3a;4848&#x2f;management&#x2f;domain&#x2f;applications&#x2f;application&#x2f;PermitSearch&#x25;3A2.2.0-SNAPSHOT&#x2f;list-sub-components&#x27;&#x3b; attrs &#x3d; &#x27;&#x7b;appname&#x3d;PermitSearch&#x25;3A2.2.0-SNAPSHOT, id&#x3d;PermitSearch&#x3a;2.2.0-SNAPSHOT&#x7d;&#x27;]]



[2022-08-15T09:33:23.967-0400] [glassfish 6.2] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=36 _ThreadName=admin-listener(1)] [timeMillis: 1660570403967] [levelValue: 1000] [[

  RestResponse.getResponse&#x28;&#x29; gives FAILURE.  endpoint &#x3d; &#x27;https&#x3a;&#x2f;&#x2f;localhost&#x3a;4848&#x2f;management&#x2f;domain&#x2f;applications&#x2f;application&#x2f;PermitSearch&#x25;3A2.2.0-SNAPSHOT&#x2f;list-sub-components&#x27;&#x3b; attrs &#x3d; &#x27;&#x7b;appname&#x3d;PermitSearch&#x25;3A2.2.0-SNAPSHOT, id&#x3d;PermitSearch&#x3a;2.2.0-SNAPSHOT&#x7d;&#x27;]]



[2022-08-15T09:33:23.967-0400] [glassfish 6.2] [SEVERE] [] [org.glassfish.admingui] [tid: _ThreadID=36 _ThreadName=admin-listener(1)] [timeMillis: 1660570403967] [levelValue: 1000] [[

  Error in getSubComponents ; 

endpoint = https://localhost:4848/management/domain/applications/application/PermitSearch%3A2.2.0-SNAPSHOT/list-sub-componentsattrs={appname=PermitSearch%3A2.2.0-SNAPSHOT, id=PermitSearch:2.2.0-SNAPSHOT}method=GET]]
```

## Steps to reproduce
1. Enable Logging (see screenshot)
![glassfish-6 2 5_app-monitor-bug_config](https://user-images.githubusercontent.com/111290486/184646244-d906e60c-1f00-435e-b4c1-f1d48a703204.PNG)

2. Deploy an application using Application Version feature (using a colon to delimit the name and version id, ie - PermitSearch:2.2.0-SNAPSHOT)

3. Navigate to "server" page and open "Monitor" tab, choosing the versioned application from the "Application" dropdown list (see screenshot)
![glassfish-6 2 5_app-monitor-bug_view](https://user-images.githubusercontent.com/111290486/184646306-c12a080f-b9e9-4f71-b04f-ee7160f4be4a.PNG)

## Impact of Issue
Prevents viewing any monitored data for the versioned application or it's components.

Sorry about lack of labeling; this is my first github issue report and didn't see what labels I could use or the syntax to add them.

**Comment by OndroMih** [comment]
I reproduced this. I deployed an app with name "myapp", without a version, and then the same app with name "myapp:v2", with version "v2".

I get the same error when I invoke the REST endpoint directly for the app name "myapp:v2":

http://localhost:4848/management/domain/applications/application/myapp:v2/list-sub-components.json?appname=myapp%3Av2&id=myapp%3Av2

Another symptom of probably the same issue is that the Modules and Components in the Edit Application page, in Admin Console, doesn't contain components, while it does contain components for the app with no versions.

For "myapp" application (correct):

![image](https://github.com/user-attachments/assets/15ccb121-f76e-426d-9565-03127b390081)

For "myapp:v2" application (only first row in the table, components are missing):

![image](https://github.com/user-attachments/assets/aa11e333-0c1a-4f01-970d-834deed483f0)

**Comment by jaceabreu** [comment]
Using Glassfish 7.0.15 and GraalVM 17 now and this is still an issue?  Are there any updates to this?

**Comment by OndroMih** [comment]
Hi, @jaceabreu , unfortunately, not progress on this. This is rather an edge case and low priority, compared to other things the GlassFish team is working on.

If you need a fix for this soon, I suggest contacting the OmniFish team at https://omnifish.ee/contact-us/ and ask about commercial options to help you. If you need this for a community/open-source project, please describe the project and we'll try to help you for free.
