### ISSUE TITLE
Documentation: Remove references to Update Tool in the documentation guides

### ISSUE THREAD

**Issue by OndroMih** [eclipse-ee4j/glassfish#24304]
Some GlassFish guides reference the Update Tool, which doesn't exist in Eclipse GlassFish anymore.

For example, in the Application Development Guide, in chapter 5 about the Jakarta EE Service Engine:

![image](https://user-images.githubusercontent.com/2195988/220473722-fa6ac3ca-f59e-431f-9f5f-1b22b3ad50cb.png)

Mentions of some other features not present in Eclipse GlassFish should also be removed. For example, I'm not sure whether the Jakarta EE Service Engine is still available - if not, it should be removed from the guides too.

**Comment by Ariho-Seth** [comment]
Hello @OndroMih, I checked the codebase and it looks like this issue was fixed, because I tried to make a search and no file was reflecting with the update tool, or maybe you can please link the adoc file that needs to be updated.

Otherwise, I request that this issue be closed too, in case it's not valid anymore. Thanks!

**Comment by OndroMih** [comment]
Hi, @Ariho-Seth , I still see a lot of references to the Update Tool in the guides: https://github.com/search?q=repo%3Aeclipse-ee4j%2Fglassfish+%22Update+Tool%22+language%3AAsciiDoc&type=code&l=AsciiDoc

Maybe it was removed in the above example, but not everywhere.
